### ISSUE TITLE
[Question] Unpacking a sequence for `keyby()` ? 

### ISSUE THREAD

**Issue by deankeinan** [dgilland/fnc#4]
Hi! I've been making heavy use of fnc for a freelance project that involves reshaping data and I've found it to be very helpful! So thank you :) happy to sponsor if you set it up.

Question: 
I may be too deep in the weeds to figure this out on my own, but I'm combing through the docs to see if some combination of iterees can help.

I have a sequence of the following shape (just a minimal example here) :

```python
[
      {
        "letter": "a",
        "words": [ "apples", "art" ]
      },
      {
       "letter":"b",
       "words":[ "bananas","bicycle"]
      },
      #...
]
```

and what I'd like is to key these by the sequence nested within each object.
So the minimal example (with the `words` sequence omitted for brevity):
```python
{
  "apples": {
    "letter": "a"
  },
  "art": {
    "letter": "a"
  },
  "bananas":{
       "letter":"b"
  },
  "bicycle":{
       "letter":"b"
  }
}
```

am I missing something obvious? as of now the way I'd do this is splitting out the data structures but I'm curious if there's a clever combination of iterees that may help with this.

my original intuition was to try something like:
```python
fnc.keyby( "words[:]" , my_seq )
```
since 
```python
fnc.keyby("words[0]", my_seq ) 
```
is valid

**Comment by dgilland** [comment]
The `keyby` function doesn't support unpacking into multiple keys, although, that is an interesting idea.

However, implementing that kind of functionality as a standalone function seems fairly straight-forward:

```python
import fnc

def keyfrom(iteratee, seq):
    iteratee = fnc.iteratee(iteratee)
    result = {}
    for item in seq:
        keys = iteratee(item)
        for key in keys:
            result[key] = item
    return result
```

which could then be used like:

```python
data = [
    {
        "letter": "a",
        "words": ["apples", "art"]
    },
    {
        "letter": "b",
        "words": ["bananas", "bicycle"]
    },
]

result = keyfrom("words", data)
print(result)
```

which would yield:

```python
{
    "apples": {
        "letter": "a",
        "words": ["apples", "art"]
    },
    "art": {
        "letter": "a",
        "words": ["apples", "art"]
    },
    "bananas": {
        "letter": "b",
        "words": ["bananas", "bicycle"]
    },
    "bicycle": {
        "letter": "b",
        "words": ["bananas", "bicycle"]
    }
}
```
